language: ruby
bundler_args: --without development

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"

services:
  - mongodb
  - redis-server

matrix:
  include:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-19mode
      jdk: openjdk7
      env: JRUBY_OPTS="-Xmx512m -Xcompile.invokedynamic=false"
    - rvm: jruby-head
      jdk: openjdk7
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
      jdk: openjdk7
      env: JRUBY_OPTS="-Xmx512m -Xcompile.invokedynamic=false"
    - rvm: jruby-head
      jdk: openjdk7
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"

before_script:
  - mongo ruby_china_test --eval 'db.addUser("travis", "test");'
  - cp config/config.yml.default config/config.yml
  - cp config/mongoid.yml.default config/mongoid.yml
  - cp config/redis.yml.default config/redis.yml
  - sed -i "s/SETUP_DEVELOPMENT_HOST/127.0.0.1:27017/g" config/mongoid.yml
  - sed -i "s/SETUP_REDIS_HOST/127.0.0.1/g" config/redis.yml
  - sed -i "s/SETUP_REDIS_PORT/6379/g" config/redis.yml

script: bundle exec rake spec jasmine:ci
